// Per-user notifications generated by admin actions.
//
// Separate from `announcements` — see comment on the table in schema.ts. Every function here
// is either "admin writes one" or "user reads / marks their own". Nobody else can mark a
// notification read on somebody else's behalf: the mark path takes both a notification id
// AND the user id, and the WHERE requires both, so a copy-pasted id can't dismiss another
// member's banner.

import { and, desc, eq, isNull } from "drizzle-orm";
import { db } from "@/lib/db";
import { userNotifications, type UserNotification } from "@/lib/db/schema";

/**
 * Known notification kinds. Text, not an enum, so a new kind ships without a migration —
 * but every place we CREATE a notification should pick from this list so the UI can style
 * consistently. Renderers fall back to a neutral style for anything unknown.
 */
export const NOTIFICATION_KINDS = [
  "credit_awarded",
  "credit_adjusted",
  "admin_note",
] as const;

export type NotificationKind = (typeof NOTIFICATION_KINDS)[number];
export type NotificationSeverity = "info" | "success" | "warning";

export async function createUserNotification(input: {
  userId: string;
  kind: NotificationKind | string;
  title: string;
  body?: string | null;
  severity?: NotificationSeverity;
}): Promise<UserNotification> {
  const [row] = await db
    .insert(userNotifications)
    .values({
      userId: input.userId,
      kind: input.kind,
      title: input.title.trim(),
      body: input.body?.trim() || null,
      severity: input.severity ?? "info",
    })
    .returning();
  return row;
}

/** Unread notifications for a user, newest first. What the dashboard banner reads. */
export async function listUnreadNotifications(userId: string): Promise<UserNotification[]> {
  return db
    .select()
    .from(userNotifications)
    .where(and(eq(userNotifications.userId, userId), isNull(userNotifications.readAt)))
    .orderBy(desc(userNotifications.createdAt));
}

/**
 * Every notification for a user, read or not. Used on the admin-profile view to show the
 * audit trail of banners the admin has fired at this account.
 */
export async function listAllNotifications(userId: string): Promise<UserNotification[]> {
  return db
    .select()
    .from(userNotifications)
    .where(eq(userNotifications.userId, userId))
    .orderBy(desc(userNotifications.createdAt));
}

/**
 * Mark a single notification read. Requires BOTH the id AND the user id — a request from
 * user A cannot dismiss user B's notification even with the correct notification id, so a
 * server action fed a leaked id from another account is a no-op.
 */
export async function markNotificationRead(
  notificationId: string,
  userId: string
): Promise<boolean> {
  const rows = await db
    .update(userNotifications)
    .set({ readAt: new Date() })
    .where(
      and(
        eq(userNotifications.id, notificationId),
        eq(userNotifications.userId, userId),
        isNull(userNotifications.readAt)
      )
    )
    .returning({ id: userNotifications.id });
  return rows.length > 0;
}

/** Bulk mark-read for a "dismiss all" button, if we ever add one. */
export async function markAllNotificationsRead(userId: string): Promise<number> {
  const rows = await db
    .update(userNotifications)
    .set({ readAt: new Date() })
    .where(and(eq(userNotifications.userId, userId), isNull(userNotifications.readAt)))
    .returning({ id: userNotifications.id });
  return rows.length;
}
